### ISSUE TITLE
Add support for Apache Omid

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/hbase-operator#398]
Add support for [Apache Omid](https://omid.apache.org/)

The research status is documented in https://app.nuclino.com/Stackable/Engineering/HBase---Phoenix---Omid-integration-and-history-bb8a4c44-c6e4-4bb8-b159-09ad755fa7be.

The proof of concept seems not to be pushed to https://github.com/stackabletech/.

The customer asked which SDP version he could expect this to be available in.
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/docker-images/issues/492
- [ ] Add HBase operator role
- [ ] Nice to have: Omid HA
- [x] Documentation. See https://app.nuclino.com/Stackable/Knowledge-Base/Deployment-and-testing-4e34fe4a-f417-4dc9-9fb5-ba8ce4c02fd7
```

**Comment by lfrancke** [comment]
We decided not to do the remaining tasks for now as we have alternative solutions (workarounds)
